name: Build
on:
  push:
    branches:
      - 'trunk'
      # The `**/*/` works around the fact that GitHub considers a leading `**/` as meaning "zero or more path components" where we want "one or more".
      - '**/*/branch-**'
  pull_request:
concurrency:
  # Cancel concurrent jobs on pull_request but not push, by including the run_id in the concurrency group for the latter.
  group: build-${{ github.event_name == 'push' && github.run_id || 'pr' }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build all projects
    runs-on: ubuntu-latest
    timeout-minutes: 20  # 2022-02-10: We've gotten the build down to ~9-15 minutes now! p9dueE-4dJ-p2
    env:
      # Hard-code a specific directory to avoid paths in vendor/composer/installed.json changing every build.
      BUILD_BASE: /tmp/jetpack-build
    outputs:
      any_plugins: ${{ steps.plugins.outputs.any }}

    steps:
      - uses: actions/checkout@v3

      - name: Check if a WordPress.com test reminder comment exists
        id: check-test-reminder-comment
        uses: actions/github-script@v6
        if: ${{ github.event_name == 'pull_request' }}
        with:
          result-encoding: string
          script: |
            const query = `query($owner:String!, $name:String!, $number:Int!) {
              repository(owner:$owner, name:$name){
                pullRequest(number:$number) {
                  comments(first: 100) {
                    nodes {
                      id
                    }
                  }
                }
              }
            }`;
            const variables = {
              owner: context.repo.owner,
              name: context.repo.repo,
              number: context.issue.number,
            };
            const comments = await github.graphql(query, variables);
            console.log( comments );
            let hasComment = false;
            comments.repository.pullRequest.comments.nodes.map( comment => {
              if ( comment.body.includes( '<!-- wpcom-reminder-comment -->' ) ) {
                hasComment = true;
              }
            } );

            return hasComment;

      - name: Post reminder to test on WordPress.com
        id: set-reminder-comment
        uses: actions/github-script@v6
        if: ${{ github.event_name == 'pull_request' && steps.check-test-reminder-comment.outputs.result != true }}
        with:
          result-encoding: string
          script: |
            const { data: { id } } = await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '<!-- wpcom-reminder-comment -->Are you an Automattician? The PR will need to be tested on WordPress.com. This comment will be updated with testing instructions as soon the build is complete.',
            });
            return id;

      - name: Other build steps happen here
        run: |
            echo 'Building Jetpack...'
      
      - name: Update reminder with Testing instructions
        id: update-reminder-comment
        uses: actions/github-script@v6
        if: ${{ github.event_name == 'pull_request' && steps.set-reminder-comment.outputs.result != null }}
        env:
          BRANCH_NAME: ${{ github.head_ref }}
          COMMENT_ID: ${{ steps.set-reminder-comment.outputs.result }}
        with:
          script: |
            const { BRANCH_NAME, COMMENT_ID } = process.env;
            const commentBody = `<!-- wpcom-reminder-comment -->Are you an Automattician? You can now test your Pull Request on WordPress.com. On your sandbox, run \`bin/jetpack-downloader test jetpack ${ BRANCH_NAME }\` to get started.`;
            await github.rest.issues.updateComment( {
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody,
              comment_id: ${ COMMENT_ID },
            } );

