
name: 'Mark stale issues'
on:
  push

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Mark issues and pull requests as stale
        id: stale
        uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # Message to be added to stale issues.
          stale-issue-message: 'This issue is stale because 720 days have passed with no activity. A member of the Dotcom Product Ambassadors Guild will review and if required close this issue within 7 days. If you disagree and would like this issue to remain open, please provide additional context, updated reproduction steps and/or screenshots.'
          # Days before issue is considered stale.
          days-before-issue-stale: 2
          # Override stale setting for PRs.
          days-before-pr-stale: -1
          # Exempted issue labels.
          exempt-issue-labels: '[Pri] High,[Pri] BLOCKER,[Status] Keep Open,'
          # Message to be added to stale PRs.
          stale-pr-message: 'This PR has been marked as stale due to lack of activity within the last 30 days.'
          # Exempted PR labels.
          exempt-pr-labels: '[Pri] High,[Pri] BLOCKER,[Status] Keep Open'
          # Disable auto-close of both issues and PRs.
          days-before-close: -1
          # Get issues in ascending (oldest first) order.
          ascending: true
          # Label to apply when issue is marked stale.
          stale-issue-label: '[Status] Stale'
          # Label to apply when PR is marked as stale.
          stale-pr-label: '[Status] Stale'
          # Increase number of operations executed per run.
          operations-per-run: 525
      - name: Build Stale issues list
        id: stale-build-list
        # Run some javascript to loop through the steps.stale.outputs.staled-issues-prs array, and build a list of stale issues.
        run: |
          const staleIssues = steps.stale.outputs.staled-issues-prs;
          let staleIssuesList = '';
          staleIssues.forEach(function(issue) {
            if ( true === issue.markedStaleThisRun ) {
                staleIssuesList += `\\n- [#${issue.number}](https://github.com/jeherve/test-actions/issues/${issue.number}) ${issue.title}`;
            }
          });
          console.log(`::set-output name=staled-issues::${staleIssuesList}`);
      - name: Post about Stale issues on Slack
        id: stale-post-slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: 'CN2FSK7L4'
          payload: |
            {
                "text": "The following issues have been marked as stale. Please review them and take appropriate action.",
                "blocks": [
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": The following issues have been marked as stale. Please review them and take appropriate action:\\n ${{ steps.stale-build-list.outputs.staled-issues }}"
                        }
                    }
                ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
